name: pathology_videos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  video_player: ^2.4.7
  file_picker: ^5.2.2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.3
  video_thumbnail: ^0.5.3
  video_player_win: ^2.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/thumb48.png
    - assets/thumb96.png
